(defun traducir-datos ()
  (with-open-file (in "datos_intermedios.lisp" :direction :input)
    (let ((datos (read in)))
      (with-open-file (out "hechos_generados.pl" :direction :output :if-exists :supersede)
        (dolist (registro datos)
          (let ((tipo (car registro)))
            (cond
              ((eq tipo 'libro)
               (format out "libro_autor('~a', '~a').~%" (cadr registro) (caddr registro))
               (format out "libro_genero('~a', '~a').~%" (cadr registro) (cadddr registro)))
              ((eq tipo 'disponible)
               (when (string-equal (caddr registro) "True")
                 (format out "disponible('~a').~%" (cadr registro))))
              ((eq tipo 'le_gusto)
               (format out "le_gusto_genero('~a', '~a').~%" (cadr registro) (caddr registro))
               (format out "le_gusto_autor('~a', '~a').~%" (cadr registro) (cadddr registro)))
              ;; --- NUEVA REGLA LISP: Traducir los libros leídos ---
              ((eq tipo 'ya_leyo)
               (format out "ya_leyo('~a', '~a').~%" (cadr registro) (caddr registro))))))))))
(traducir-datos)